"""
Django settings for snappy2 project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from decouple import config, Csv
from unipath import Path


BASE_DIR = Path(__file__).parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)
DEBUG_PROPAGATE_EXCEPTIONS = config(
    'DEBUG_PROPAGATE_EXCEPTIONS',
    False,
    cast=bool,
)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv(), default='localhost')


INSTALLED_APPS = [
    'snappy2.symbolicate',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'snappy2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snappy2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# XXX python-decouple!
CACHES = {
    # Use this for all minor caching needs like sessions or
    # web caching etc.
    # The max value size is 1MB and by default the memcache backend
    # swallows ALL errors.
    'default': {
        'BACKEND': config(
            'CACHE_BACKEND',
            # 'django.core.cache.backends.locmem.LocMemCache',
            'django.core.cache.backends.memcached.MemcachedCache',
        ),
        'LOCATION': config(
            'CACHE_LOCATION',
            # 'snowflake',
            '127.0.0.1:11211'
        ),
        'TIMEOUT': config('CACHE_TIMEOUT', 500, cast=int),
        'KEY_PREFIX': config('CACHE_KEY_PREFIX', 'snappy2'),
    },
    'redis': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config(
            'REDIS_URL',
            'redis://127.0.0.1:6379/1'
        ),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


SYMBOL_URLS = config(
    'SYMBOL_URLS',
    cast=Csv(),
    default=(
        'https://s3-us-west-2.amazonaws.com/org.mozilla.crash-stats.symbols-public/v1/'
    )
)

for url in SYMBOL_URLS:
    assert url.endswith('/'), url


# Set this to something like '/tmp/symbols' to have all downloads
# stored on disk.
DEBUG_SAVE_SYMBOLS = config(
    'DEBUG_SAVE_SYMBOLS',
    default=None,
)
